---

- name: Copy idle shutdown script to remote machine
  copy:
    src: idleshutdown.sh
    dest: "{{ script_dest_path }}"
    mode: '0755'

- name: Copy systemd service file to remote machine
  copy:
    src: idleshutdown.service
    dest: "{{ service_dest_path }}"
    mode: '0644'
  notify:
    - Reload systemd daemon

- name: Flush handlers
  meta: flush_handlers

- name: Enable and start the idle shutdown service
  systemd:
    name: idleshutdown.service
    enabled: yes
    state: started
