vrrp_scrip chk_haproxy {
	script "/usr/bin/pgrep haproxy"
	interval 2
	weight -10
}

vrrp_instance VI_1 {
	state MASTER
	interface ens37
	virtual_router_id 52
	priority 100
	advert_int 1
	unicast_src_ip aaa.aaa.aaa.aaa  # Insert IP of the interface for health checks between nodes here

	unicast_peer {
		bbb.bbb.bbb.bbb  # Insert IP of remote peer interface for health checks between nodes here
	}

	authentication {
		auth_type PASS
		auth_pass [REDACTED]
	}

	virtual_ipaddress {
		xxx.xxx.xxx.xxx/24 dev ens33 # This is to be replaced with the public IP mapped to the domain
	}
	
	garp_master_delay 1
	garp_master_repeat 5
	garp_master_refresh 10

	track_script {
		chk_haproxy
	}
}
